[2021-11-21 10:01:40 +0100] [100578] [INFO] Starting gunicorn 20.0.4
[2021-11-21 10:01:40 +0100] [100578] [INFO] Listening at: http://0.0.0.0:4911 (100578)
[2021-11-21 10:01:40 +0100] [100578] [INFO] Using worker: sync
[2021-11-21 10:01:40 +0100] [100581] [INFO] Booting worker with pid: 100581
[2021-11-21 10:01:40 +0100] [100581] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 383, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dsso'
[2021-11-21 10:01:40 +0100] [100581] [INFO] Worker exiting (pid: 100581)
[2021-11-21 10:01:40 +0100] [100578] [INFO] Shutting down: Master
[2021-11-21 10:01:40 +0100] [100578] [INFO] Reason: Worker failed to boot.
[2021-11-21 10:01:45 +0100] [100583] [INFO] Starting gunicorn 20.0.4
[2021-11-21 10:01:45 +0100] [100583] [INFO] Listening at: http://0.0.0.0:4911 (100583)
[2021-11-21 10:01:45 +0100] [100583] [INFO] Using worker: sync
[2021-11-21 10:01:45 +0100] [100585] [INFO] Booting worker with pid: 100585
[2021-11-21 10:01:45 +0100] [100585] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 383, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dsso'
[2021-11-21 10:01:45 +0100] [100585] [INFO] Worker exiting (pid: 100585)
[2021-11-21 10:01:45 +0100] [100583] [INFO] Shutting down: Master
[2021-11-21 10:01:45 +0100] [100583] [INFO] Reason: Worker failed to boot.
